# Generated by Django 5.2.7 on 2026-02-23 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_uploadeddocument_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk', models.CharField(max_length=20)),
                ('risk_score', models.FloatField()),
                ('high_risk_items', models.IntegerField()),
                ('analysis_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='backend.uploadeddocument')),
            ],
        ),
    ]
